# Base image
FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# System dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy only requirements first
COPY requirements_rest.txt /app/
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements_rest.txt

# Copy project files
COPY . /app/

CMD ["python", "manage.py", "runserver", "0.0.0.0:8002"]
