# Generated by Django 4.2.23 on 2025-08-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='equipment',
        ),
        migrations.AddField(
            model_name='room',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='booking.equipment'),
        ),
    ]
