# Generated by Django 4.2.23 on 2025-08-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_category_rename_date_booking_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(help_text='Enter number of guests (e.g., 1, 2, 3)'),
        ),
    ]
